config/routes.rb
Rails.application.routes.draw do
	get 'pages/home'

	get 'attendance/new'
	get 'attendance/index'
	
	resources :students
	resources :subjects
	resources :holidays
	resources :working_days
	resources :leaves
	resources :time_tables
	# resources :attendance

	devise_for :admins

	devise_scope :admin do
		root to: "devise/sessions#new"
	end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :students
  has_many :subjects
  has_many :holidays
  has_many :working_days
  has_one :time_table
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	belongs_to :student

	# before_save :generate

	# private

	def generate admin
		holidays = admin
					.holidays.where(date: [self.start_date .. self.end_date])
					.map(&:date)
					.collect { |d| d.strftime('%A').downcase }
		weekdays = (self.start_date.to_date .. self.end_date.to_date).select(&:on_weekday?).collect { |d| d.strftime('%A').downcase }
		subjects = admin.subjects.map(&:name).collect { |s| s.downcase }
		extra_working_days = admin.working_days
					.where(date: [self.start_date .. self.end_date])
					.map(&:weekday).map(&:to_s)
		leaves = self.student.leaves
					.where(date: [self.start_date .. self.end_date])
					.map(&:date).collect { |d| d.strftime('%A').downcase }
		table = admin.time_table.table

		self.total_hours = total_hours_in_given_range table, subjects, weekdays, holidays, extra_working_days
		self.student_hours = subtract_hours table, total_hours, leaves
		self.percentage = percentage_hours self.total_hours, self. student_hours
	end

	def add_hours table, hours, days
		days.inject(hours) { |total, day| total.merge(table[day]) { |_,x,y| x + y }}
	end

	def subtract_hours table, hours, days
		days.inject(hours) { |total, day| total.merge(table[day]) { |_,x,y| x - y }}
	end

	def percentage_hours total_hours, student_hours
		student_hours.merge(total_hours) { |_,x,y| ((x * 100.0) / y).round(2) }
	end

	def total_hours_in_given_range table, subjects, weekdays, holidays, extra_working_days

		hours = Hash[subjects.zip(Array.new(subjects.size, 0))]
		# Add working day hours
		hours = add_hours table, hours, weekdays # weekdays.inject(hours) { |total, day| total.merge(table[day]) { |_,x,y| x + y }}
		# Subtract holiday day hours
		hours = subtract_hours table, hours, holidays # holidays.inject(hours) { |total, day| total.merge(table[day]) { |_,x,y| x - y }}
		# Add extra working days
		hours = add_hours table, hours, extra_working_days

		hours
	end
end

app/models/holiday.rb
class Holiday < ApplicationRecord
  belongs_to :admin

  validates :date, presence: true
end

app/models/leave.rb
class Leave < ApplicationRecord
  belongs_to :student

  validates :student_id, :date, presence: true

  enum weekday: %w[monday tuesday wednesday thursday friday]
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :admin
  has_many :leaves
  
  validates :name, :roll_no, :admission_no, presence: true
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :admin
  validates :name, :code, presence: true
end

app/models/time_table.rb
class TimeTable < ApplicationRecord
  belongs_to :admin

  attr_accessor :table_string
end

app/models/working_day.rb
class WorkingDay < ApplicationRecord
  belongs_to :admin

  validates :date, :weekday, presence: true

  enum weekday: %w[monday tuesday wednesday thursday friday]
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
	before_action :authenticate_admin!

	def new
	end

	def create
		@holiday = Holiday.new(holiday_params)
        @holiday.admin = current_admin
        if @holiday.save
            # flash[:success] = I18n.t("article.create_success_message")
            redirect_to holidays_path
        else
            flash[:error] = @holiday.errors.full_messages
            render :new
        end
	end

	def index
		@holidays = current_admin.holidays
	end

    def destroy
        holiday = Holiday.find(params[:id])
        if holiday.admin == current_admin && holiday.destroy
            flash[:success] ='Holiday deleted successfully'
        else
            flash[:danger] ='Holiday deletion failed'
        end
        redirect_to holidays_url
    end

	private

	def holiday_params
		params.require(:holiday).permit(:date, :occasion)
	end
end

app/controllers/leaves_controller.rb
class LeavesController < ApplicationController
	before_action :authenticate_admin!
	
	def new
		@students = current_admin.students
	end

	def create
		@leaves = Leave.new(leave_params)
        date = leave_params[:date].to_date
        if date && date.on_weekday?
            @leaves.weekday = date.strftime('%A').downcase.to_sym
        else
            working_days = WorkingDay.where(date: date)
            if working_days.empty?
                flash[:error] = 'Given day is not added as working day'
                render :new
                return
            end
            @leaves.weekday = working_days.first.weekday
        end
		if @leaves.save
            redirect_to leaves_path
        else
        	flash[:error] = @leaves.errors.full_messages
        	render :new
        end
    end

    def index
        @students = current_admin.students
        @current_student = @students.first
        if params[:student]
            student_id = params[:student][:student_id]
            @current_student = @students.find(student_id)
        end
        @leaves = @current_student.leaves.preload(:student) unless @students.empty?
    end

    def destroy
        leave = Leave.find(params[:id])
        if leave.admin == current_admin && leave.destroy
            flash[:success] ='Leave deleted successfully'
        else
            flash[:danger] ='Leave deletion failed'
        end
        redirect_to leaves_url
    end

    private

    def leave_params
    	params.require(:leave).permit(:reason, :date, :student_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_admin!

	def home
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    before_action :authenticate_admin!

    def create
        @student = Student.new(student_params)
        @student.admin = current_admin
        if @student.save
            redirect_to students_path
        else
            flash[:error] = @student.errors.full_messages
            render :new
        end
    end

    def new
    end

    def edit
    end

    def destroy
        student = Student.find(params[:id])
        if student.admin == current_admin && student.destroy
            flash[:success] ='Student deleted successfully'
        else
            flash[:danger] ='Student deletion failed'
        end
        redirect_to students_url
    end

    def index
        @students = current_admin.students
    end

    private

    def student_params
        params.require(:student).permit(:name, :roll_no, :admission_no, :ktu_id)
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
	before_action :authenticate_admin!

	def new
	end

	def create
		@subject = Subject.new(subject_params)
		@subject.admin = current_admin
		if @subject.save
            redirect_to subjects_path
        else
        	flash[:error] = @subject.errors.full_messages
        	render :new
        end
    end

    def edit
    end

    def index
    	@subjects = current_admin.subjects
    end

    def destroy
        subject = Subject.find(params[:id])
        if subject.admin == current_admin && subject.destroy
            flash[:success] ='Subject deleted successfully'
        else
            flash[:danger] ='Subject deletion failed'
        end
        redirect_to subjects_url
    end

    private

    def subject_params
        params.require(:subject).permit(:name, :code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendance_helper.rb
module AttendanceHelper
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/time_tables_helper.rb
module TimeTablesHelper
end

app/helpers/working_days_helper.rb
module WorkingDaysHelper
end

app/views/holidays/index.html.slim
.row
	.col-12
		h3.header Holidays
		.table-scrollable
			table.table
				thead
					tr
						th Occasion
						th Date
						th Week Day
						th style="width: 5%"
				tbody
					- @holidays.each do |holiday|
						tr
							td = holiday.occasion
							td = holiday.date.strftime('%B %d, %Y')
							td = holiday.date.strftime('%A')
							td = link_to "✖", holiday, data: { method: 'delete', confirm: 'Are you sure?' }

		= link_to 'Add a new holiday', new_holiday_url	

app/views/holidays/new.html.slim
= render '/flash'

.row.justify-content-center
	.col-6
		h3.header Create Holiday
		= form_tag :holidays
			.form-group
				= label :holiday, :occasion
				= text_field :holiday, :occasion, class: 'form-control'
			.form-group
				= label :holiday, :date
				= text_field :holiday, :date, class: 'form-control datepicker', id: 'datepicker'
			.form-group
				= submit_tag :submit, value: 'Create', class: 'btn btn-dark'

app/views/leaves/_leaves_for_student.html.slim
= form_tag :leaves, method: :get, class: 'form form-inline select-student'
	.form-group.mx-sm-3.mb-2	
		= collection_select :student, :student_id, @students, :id, :name, { include_blank: '' }, { class: "form-control" }
	.form-grop.mx-sm-3.mb-2
		= submit_tag 'Show', class: 'btn btn-dark'

app/views/leaves/delete.html.slim
h1 Leaves#delete
p Find me in app/views/leaves/delete.html.slim

app/views/leaves/index.html.slim
.row
	.col-12
		h3.header Leaves
		- if @students.present?
			= render 'leaves_for_student'
			
			h5 = @current_student.name
			table.table
				thead
					tr
						th Student
						th Date
						th Reason
						th Weekday
						th style="width: 5%"
				tbody
					- @leaves.each do |leave|
						tr
							td = leave.student.name
							td = leave.date.strftime('%B %d, %Y')
							td = leave.reason
							td = leave.weekday.humanize
							td = link_to "✖", leave, data: { method: 'delete', confirm: 'Are you sure?' }

			= link_to 'Add a new leave', new_leave_url	
		- else
			p First, add students. Then add as many leaves as you want! 😌

app/views/leaves/new.html.slim
= render '/flash'

.row.justify-content-center
	.col-6
		h3.header Create Leave
		= form_tag :leaves
			.form-group
				= label :leave, :student
				= collection_select :leave, :student_id, @students, :id, :name, {}, { class: "form-control" }

			.form-group
				= label :leave, :reason
				= text_field :leave, :reason, class: 'form-control'
			.form-group
				= label :leave, :date
				= text_field :leave, :date, class: 'form-control datepicker', id: 'datepicker'
				small If you are adding a weekend, make sure you've added that as a working day first
			.form-grop
				= submit_tag :submit, value: 'Create', class: 'btn btn-dark'

app/views/students/edit.html.slim
h1 Students#edit
p Find me in app/views/students/edit.html.slim

app/views/students/index.html.slim
.row
	.col-12
		h3.header Students
		.table-scrollable
			table.table
				thead
					tr
						th Name
						th Roll Number
						th Admission Number
						th KTU ID
						th style="width: 5%"
				tbody
					- @students.each do |student|
						tr
							td = student.name 
							td = student.roll_no
							td = student.admission_no
							td = student.ktu_id
							td = link_to "✖", student, data: { method: 'delete', confirm: 'Are you sure?' }

		= link_to 'Add a new student', new_student_url	

app/views/students/new.html.slim
= render '/flash'

.row.justify-content-center
	.col-6
		h3.header Create Student
		= form_tag :students
			.form-group
				= label :student, :name
				= text_field :student, :name, class: 'form-control'
			.form-group
				= label :student, :roll_no
				= text_field :student, :roll_no, class: 'form-control'
			.form-group
				= label :student, :admission_no
				= text_field :student, :admission_no, class: 'form-control'
			.form-group
				= label :student, :ktu_id
				= text_field :student, :ktu_id, class: 'form-control'
			.form-grop
				= submit_tag :submit, value: 'Create', class: 'btn btn-dark'

app/views/subjects/edit.html.slim
h1 Subjects#edit
p Find me in app/views/subjects/edit.html.slim

app/views/subjects/index.html.slim
.row
	.col-12
		h3.header Subjects
		table.table
			thead
				tr
					th Name
					th Code
					th style="width: 5%"
			tbody
				- @subjects.each do |subject|
					tr
						td = subject.name 
						td = subject.code
						td = link_to "✖", subject, data: { method: 'delete', confirm: 'Are you sure?' }
		
		= link_to 'Add a new subject', new_subject_url	

app/views/subjects/new.html.slim
= render '/flash'

.row.justify-content-center
	.col-6
		h3.header Create Subject
		= form_tag :subjects
			.form-group
				= label :subject, :name
				= text_field :subject, :name, class: 'form-control'
			.form-group
				= label :subject, :code
				= text_field :subject, :code, class: 'form-control'
			.form-grop
				= submit_tag :submit, value: 'Create', class: 'btn btn-dark'