config/routes.rb
Rails.application.routes.draw do
	get 'pages/home'

	get 'attendance/new'
	get 'attendance/index'
	
	resources :students
	resources :subjects
	resources :holidays
	resources :working_days
	resources :leaves
	resources :time_tables
	# resources :attendance

	devise_for :admins

	devise_scope :admin do
		root to: "devise/sessions#new"
	end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :students
  has_many :subjects
  has_many :holidays
  has_many :working_days
  has_one :time_table
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	belongs_to :student

	# before_save :generate

	# private

	def generate admin
		holidays = admin
					.holidays.where(date: [self.start_date .. self.end_date])
					.map(&:date)
					.collect { |d| d.strftime('%A').downcase }
		weekdays = (self.start_date.to_date .. self.end_date.to_date).select(&:on_weekday?).collect { |d| d.strftime('%A').downcase }
		subjects = admin.subjects.map(&:name).collect { |s| s.downcase }
		extra_working_days = admin.working_days
					.where(date: [self.start_date .. self.end_date])
					.map(&:weekday).map(&:to_s)
		leaves = self.student.leaves
					.where(date: [self.start_date .. self.end_date])
					.map(&:date).collect { |d| d.strftime('%A').downcase }
		table = admin.time_table.table

		self.total_hours = total_hours_in_given_range table, subjects, weekdays, holidays, extra_working_days
		self.student_hours = subtract_hours table, total_hours, leaves
		self.percentage = percentage_hours self.total_hours, self. student_hours
	end

	def add_hours table, hours, days
		days.inject(hours) { |total, day| total.merge(table[day]) { |_,x,y| x + y }}
	end

	def subtract_hours table, hours, days
		days.inject(hours) { |total, day| total.merge(table[day]) { |_,x,y| x - y }}
	end

	def percentage_hours total_hours, student_hours
		student_hours.merge(total_hours) { |_,x,y| ((x * 100.0) / y).round(2) }
	end

	def total_hours_in_given_range table, subjects, weekdays, holidays, extra_working_days

		hours = Hash[subjects.zip(Array.new(subjects.size, 0))]
		# Add working day hours
		hours = add_hours table, hours, weekdays # weekdays.inject(hours) { |total, day| total.merge(table[day]) { |_,x,y| x + y }}
		# Subtract holiday day hours
		hours = subtract_hours table, hours, holidays # holidays.inject(hours) { |total, day| total.merge(table[day]) { |_,x,y| x - y }}
		# Add extra working days
		hours = add_hours table, hours, extra_working_days

		hours
	end
end

app/models/holiday.rb
class Holiday < ApplicationRecord
  belongs_to :admin

  validates :date, presence: true
end

app/models/leave.rb
class Leave < ApplicationRecord
  belongs_to :student

  validates :student_id, :date, presence: true

  enum weekday: %w[monday tuesday wednesday thursday friday]
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :admin
  has_many :leaves
  
  validates :name, :roll_no, :admission_no, presence: true
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :admin
  validates :name, :code, presence: true
end

app/models/time_table.rb
class TimeTable < ApplicationRecord
  belongs_to :admin

  attr_accessor :table_string
end

app/models/working_day.rb
class WorkingDay < ApplicationRecord
  belongs_to :admin

  validates :date, :weekday, presence: true

  enum weekday: %w[monday tuesday wednesday thursday friday]
end

app/controllers/leaves_controller.rb
class LeavesController < ApplicationController
	before_action :authenticate_admin!
	
	def new
		@students = current_admin.students
	end

	def create
		@leaves = Leave.new(leave_params)
        date = leave_params[:date].to_date
        if date && date.on_weekday?
            @leaves.weekday = date.strftime('%A').downcase.to_sym
        else
            working_days = WorkingDay.where(date: date)
            if working_days.empty?
                flash[:error] = 'Given day is not added as working day'
                render :new
                return
            end
            @leaves.weekday = working_days.first.weekday
        end
		if @leaves.save
            redirect_to leaves_path
        else
        	flash[:error] = @leaves.errors.full_messages
        	render :new
        end
    end

    def index
        @students = current_admin.students
        @current_student = @students.first
        if params[:student]
            student_id = params[:student][:student_id]
            @current_student = @students.find(student_id)
        end
        @leaves = @current_student.leaves.preload(:student) unless @students.empty?
    end

    def destroy
        leave = Leave.find(params[:id])
        if leave.admin == current_admin && leave.destroy
            flash[:success] ='Leave deleted successfully'
        else
            flash[:danger] ='Leave deletion failed'
        end
        redirect_to leaves_url
    end

    private

    def leave_params
    	params.require(:leave).permit(:reason, :date, :student_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_admin!

	def home
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendance_helper.rb
module AttendanceHelper
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/time_tables_helper.rb
module TimeTablesHelper
end

app/helpers/working_days_helper.rb
module WorkingDaysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IP-HUB</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
  <%= render "pages/navbar" %>
  <div class="container main">
    <% if admin_signed_in? %>
    <div class="row main-row">
      <div class="col-2 sidebar">
        <%= render "pages/sidebar" %>
      </div>
      <div class="col-10 content-area">
        <div class="content">
          <%= yield %>
        </div>
      </div>
    </div>
    <% else %>
    <div class="content">
      <%= yield %>
    </div>
  </div>
  <% end %>

</body>
</html>

app/views/pages/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark">
	<a class="navbar-brand" href="#">IP-HUB</a>
	<div class="collapse navbar-collapse" id="navbarTogglerDemo02">
		<ul class="navbar-nav mr-auto mt-2 mt-lg-0">
			<!-- <li class="nav-item active">
				<a class="nav-link" href="/pages/home">Home <span class="sr-only">(current)</span></a>
			</li> -->
			<!-- <li class="nav-item">
				<a class="nav-link" href="#">Link</a>
			</li>
			<li class="nav-item">
				<a class="nav-link disabled" href="#">Disabled</a>
			</li> -->
		</ul>

		<% if admin_signed_in? %>
		<%= link_to 'Sign Out', destroy_admin_session_url, class: 'sign-out' %>
		<% end %>
	</div>
</nav>

app/views/pages/_sidebar.html.slim
.sidebar-items
	.sidebar-item 
		i.fa.fa-home
		= link_to 'Home', pages_home_url
	.sidebar-item 
		i.fa.fa-user-circle-o
		= link_to 'Students', students_url
	.sidebar-item 
		i.fa.fa-book
		= link_to 'Subjects', subjects_url
	.sidebar-item 
		i.fa.fa-calendar 
		= link_to 'Time Table', time_tables_url
	.sidebar-item 
		i.fa.fa-calendar-times-o 
		= link_to 'Holidays', holidays_url
	.sidebar-item 
		i.fa.fa-book 
		= link_to 'Working Days', working_days_url
	.sidebar-item 
		i.fa.fa-calendar-check-o 
		= link_to 'Leaves', leaves_url
	.sidebar-item 
		i.fa.fa-address-book-o
		= link_to 'Attendance Details', attendance_new_url
	.sidebar-item 
		i.fa.fa-gears 
		= link_to 'Settings', '#'

app/views/pages/home.html.slim
.flash-message
  - flash.each do |key, value|
  	  .alert.alert-success = value

h3.header Welcome!

p Fill in you student and subject details. Then fill in the time table, which is a little tricky. 
p Enter the holidays.
p Enter the extra working days.
p Enter the leaves for each student.
p And that's it! Genereate your attendance.